const cursorThunMeg = document.querySelector('#cursorThunMeg')
const thunMeg = document.querySelector('#thunMeg')
const cursorNinMeg = document.querySelector('#cursorNinMeg')
const ninMeg = document.querySelector('#ninMeg')
const cursorShoMeg = document.querySelector('#cursorShoMeg')
const shoMeg = document.querySelector('#shoMeg')
const cursorMegTig = document.querySelector('#cursorMegTig')
const megTig = document.querySelector('#megTig')
const cursorLipSyn = document.querySelector('#cursorLipSyn')
const lipSyn = document.querySelector('#lipSyn')
const cursorGol = document.querySelector('#cursorGol')
const gol = document.querySelector('#gol')
const cursorLorZed = document.querySelector('#cursorLorZed')
const lorZed = document.querySelector('#lorZed')
const cursorSilHor = document.querySelector('#cursorSilHor')
const silHor = document.querySelector('#silHor')

const characters = document.querySelectorAll('.character')

Array.from(characters).forEach(element => element.addEventListener('click', selectCharacter))

function selectCharacter(click) {
    if(click.target.classList.contains('thunderMegazord')){
		cursorThunMeg.classList.toggle('hidden')
        thunMeg.classList.toggle('hidden')
		cursorNinMeg.classList.add('hidden')
		ninMeg.classList.remove('hidden')
		cursorShoMeg.classList.add('hidden')
		shoMeg.classList.remove('hidden')
		cursorMegTig.classList.add('hidden')
		megTig.classList.remove('hidden')
		cursorLipSyn.classList.add('hidden')
		lipSyn.classList.remove('hidden')
		cursorGol.classList.add('hidden')
		gol.classList.remove('hidden')
		cursorLorZed.classList.add('hidden')
		lorZed.classList.remove('hidden')
		cursorSilHor.classList.add('hidden')
		silHor.classList.remove('hidden')
	}else if (click.target.classList.contains('ninjaMegazord')){
		cursorNinMeg.classList.toggle('hidden')
        ninMeg.classList.toggle('hidden')
		cursorThunMeg.classList.add('hidden')
		thunMeg.classList.remove('hidden')
		cursorShoMeg.classList.add('hidden')
		shoMeg.classList.remove('hidden')
		cursorMegTig.classList.add('hidden')
		megTig.classList.remove('hidden')
		cursorLipSyn.classList.add('hidden')
		lipSyn.classList.remove('hidden')
		cursorGol.classList.add('hidden')
		gol.classList.remove('hidden')
		cursorLorZed.classList.add('hidden')
		lorZed.classList.remove('hidden')
		cursorSilHor.classList.add('hidden')
		silHor.classList.remove('hidden')
	}else if (click.target.classList.contains('shogunMegazord')){
		cursorShoMeg.classList.toggle('hidden')
        shoMeg.classList.toggle('hidden')
		cursorNinMeg.classList.add('hidden')
		ninMeg.classList.remove('hidden')
		cursorThunMeg.classList.add('hidden')
		thunMeg.classList.remove('hidden')
		cursorMegTig.classList.add('hidden')
		megTig.classList.remove('hidden')
		cursorLipSyn.classList.add('hidden')
		lipSyn.classList.remove('hidden')
		cursorGol.classList.add('hidden')
		gol.classList.remove('hidden')
		cursorLorZed.classList.add('hidden')
		lorZed.classList.remove('hidden')
		cursorSilHor.classList.add('hidden')
		silHor.classList.remove('hidden')
	}else if (click.target.classList.contains('megaTigerzord')){
		cursorMegTig.classList.toggle('hidden')
        megTig.classList.toggle('hidden')
		cursorNinMeg.classList.add('hidden')
		ninMeg.classList.remove('hidden')
		cursorShoMeg.classList.add('hidden')
		shoMeg.classList.remove('hidden')
		cursorThunMeg.classList.add('hidden')
		thunMeg.classList.remove('hidden')
		cursorLipSyn.classList.add('hidden')
		lipSyn.classList.remove('hidden')
		cursorGol.classList.add('hidden')
		gol.classList.remove('hidden')
		cursorLorZed.classList.add('hidden')
		lorZed.classList.remove('hidden')
		cursorSilHor.classList.add('hidden')
		silHor.classList.remove('hidden')
	}else if (click.target.classList.contains('lipSyncher')){
		cursorLipSyn.classList.toggle('hidden')
        lipSyn.classList.toggle('hidden')
		cursorNinMeg.classList.add('hidden')
		ninMeg.classList.remove('hidden')
		cursorShoMeg.classList.add('hidden')
		shoMeg.classList.remove('hidden')
		cursorMegTig.classList.add('hidden')
		megTig.classList.remove('hidden')
		cursorThunMeg.classList.add('hidden')
		thunMeg.classList.remove('hidden')
		cursorGol.classList.add('hidden')
		gol.classList.remove('hidden')
		cursorLorZed.classList.add('hidden')
		lorZed.classList.remove('hidden')
		cursorSilHor.classList.add('hidden')
		silHor.classList.remove('hidden')
	}else if (click.target.classList.contains('goldar')){
		cursorGol.classList.toggle('hidden')
        gol.classList.toggle('hidden')
		cursorNinMeg.classList.add('hidden')
		ninMeg.classList.remove('hidden')
		cursorShoMeg.classList.add('hidden')
		shoMeg.classList.remove('hidden')
		cursorMegTig.classList.add('hidden')
		megTig.classList.remove('hidden')
		cursorLipSyn.classList.add('hidden')
		lipSyn.classList.remove('hidden')
		cursorThunMeg.classList.add('hidden')
		thunMeg.classList.remove('hidden')
		cursorLorZed.classList.add('hidden')
		lorZed.classList.remove('hidden')
		cursorSilHor.classList.add('hidden')
		silHor.classList.remove('hidden')
	}else if (click.target.classList.contains('lordZedd')){
		cursorLorZed.classList.toggle('hidden')
        lorZed.classList.toggle('hidden')
		cursorNinMeg.classList.add('hidden')
		ninMeg.classList.remove('hidden')
		cursorShoMeg.classList.add('hidden')
		shoMeg.classList.remove('hidden')
		cursorMegTig.classList.add('hidden')
		megTig.classList.remove('hidden')
		cursorLipSyn.classList.add('hidden')
		lipSyn.classList.remove('hidden')
		cursorGol.classList.add('hidden')
		gol.classList.remove('hidden')
		cursorThunMeg.classList.add('hidden')
		thunMeg.classList.remove('hidden')
		cursorSilHor.classList.add('hidden')
		silHor.classList.remove('hidden')
	}else if (click.target.classList.contains('silverHorns')){
		cursorSilHor.classList.toggle('hidden')
        silHor.classList.toggle('hidden')
		cursorNinMeg.classList.add('hidden')
		ninMeg.classList.remove('hidden')
		cursorShoMeg.classList.add('hidden')
		shoMeg.classList.remove('hidden')
		cursorMegTig.classList.add('hidden')
		megTig.classList.remove('hidden')
		cursorLipSyn.classList.add('hidden')
		lipSyn.classList.remove('hidden')
		cursorGol.classList.add('hidden')
		gol.classList.remove('hidden')
		cursorLorZed.classList.add('hidden')
		lorZed.classList.remove('hidden')
		cursorThunMeg.classList.add('hidden')
		thunMeg.classList.remove('hidden')
	}else {
		console.log('Ivan da ooze')
	}
}